import type { CatalogUnit, LabourCategory, PriceSourceKind } from '@/types'

/**
 * Catálogo por defecto para España (banda de mercado de la Comunidad de Madrid)
 * que se carga en el catálogo de cada empresa la primera vez que entra en
 * /catalog, para que nadie empiece con el catálogo vacío.
 *
 * Origen de los datos: borrador generado con IA a partir de guías de precios
 * públicas y revisado a mano. Son PRECIOS ORIENTATIVOS y no proceden de bases de
 * precios con licencia (BEDEC, IVE, BCCA, CYPE Generador de precios), por lo que
 * nunca deben presentarse como si vinieran de ellas.
 *
 * `base_price` es el valor de partida; `price_min` / `price_max` son la banda de
 * mercado que la app muestra al revisar el precio.
 */

/**
 * ISO date of the last hand review of the default prices. Bump it when you change a
 * price, so the catalogue can flag what has not been looked at in over a year.
 */
export const DEFAULT_CATALOG_REVISION = '2026-09-01'

/**
 * Basis stored on every seeded partida and shown under its price. It must never name
 * a licensed price base: these are our own draft figures (docs/catalogo-precios.md).
 */
export const DEFAULT_CATALOG_PRICE_SOURCE = `Borrador propio · contraste de bandas de mercado · ${DEFAULT_CATALOG_REVISION.slice(0, 7)}`

/**
 * Per-partida price recipe. `base_price` is what the app uses today; the recipe
 * fields are stored so a later job can recompute it from the construction convenio
 * (labour) and the INE IPRI series (material) instead of from a literal.
 * The table partida by partida lives in docs/catalogo-precios.md — keep both in sync;
 * `node scripts/check-catalog.mjs` verifies they agree.
 */
export interface DefaultCatalogService {
  code: string
  name: string
  description: string
  unit: CatalogUnit
  base_price: number
  price_min: number
  price_max: number
  /** What drives the cost: labour, material, both, or an administrative fee. */
  source_kind: PriceSourceKind
  /** Labour content per unit (our own productivity assumption). */
  labour_hours: number
  labour_category: LabourCategory
  /** Commodity family the material cost is anchored to; null when there is none. */
  material_anchor: string | null
  /** Basis shown in the app; never a licensed base name unless actually licensed. */
  price_source: string
  /** Public reference for this specific price; null when there is none. */
  price_source_url: string | null
  /** ISO date a human last reviewed this price. */
  price_reviewed_at: string
}

export interface DefaultCatalogPhase {
  name: string
  services: DefaultCatalogService[]
}

export const DEFAULT_CATALOG: DefaultCatalogPhase[] = [
  {
    name: 'Demoliciones y Trabajos Previos',
    services: [
      {
        code: 'DEM-001',
        name: 'Demolición de tabique de ladrillo/rasillón',
        description: 'Demolición de tabique de fábrica de ladrillo o rasillón por medios manuales, incluyendo transporte interno a punto de carga.',
        unit: 'm2',
        base_price: 14.5,
        price_min: 12,
        price_max: 18,
        source_kind: 'labour',
        labour_hours: 0.25,
        labour_category: 'peón',
        material_anchor: null,
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'DEM-002',
        name: 'Picado de alicatado o solado cerámico',
        description: 'Picado y levantado de azulejos o baldosas cerámicas existentes, incluyendo saneado del soporte.',
        unit: 'm2',
        base_price: 11,
        price_min: 9.5,
        price_max: 14,
        source_kind: 'labour',
        labour_hours: 0.2,
        labour_category: 'peón',
        material_anchor: null,
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'DEM-003',
        name: 'Desmontaje de sanitarios y grifería',
        description: 'Desmontaje de lavabo, inodoro, bidet o bañera/plato de ducha sin recuperación del elemento.',
        unit: 'ud',
        base_price: 25,
        price_min: 20,
        price_max: 35,
        source_kind: 'labour',
        labour_hours: 0.35,
        labour_category: 'of.1',
        material_anchor: null,
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'DEM-004',
        name: 'Carga y retirada de escombros a vertedero autorizado',
        description: 'Carga manual o mecánica de escombros, canon de vertedero autorizado y tasa de gestión de residuos.',
        unit: 'm3',
        base_price: 38,
        price_min: 32,
        price_max: 45,
        source_kind: 'mixed',
        labour_hours: 0.6,
        labour_category: 'peón',
        material_anchor: 'canon de vertedero',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'DEM-005',
        name: 'Protección de zonas de paso y ascensor',
        description: 'Protección de suelos, paredes y cabina de ascensor con cartón ondulado y plástico de burbuja.',
        unit: 'ud',
        base_price: 120,
        price_min: 90,
        price_max: 160,
        source_kind: 'mixed',
        labour_hours: 1.6,
        labour_category: 'peón',
        material_anchor: 'cartón ondulado y plástico',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'DEM-006',
        name: 'Desmontaje de carpintería interior y limpieza final de la zona de trabajo',
        description: 'Desmontaje de carpintería interior (puertas y ventanas) con retirada de herrajes aprovechables, desmontaje de marcos y limpieza final de la zona de trabajo.',
        unit: 'ud',
        base_price: 45,
        price_min: 30,
        price_max: 65,
        source_kind: 'labour',
        labour_hours: 0.7,
        labour_category: 'of.1',
        material_anchor: null,
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
    ],
  },
  {
    name: 'Albañilería y Ayudas de Oficio',
    services: [
      {
        code: 'ALB-001',
        name: 'Levantado de tabique de ladrillo hueco doble (7 cm)',
        description: 'Tabicón de ladrillo hueco doble tomado con mortero de cemento, listo para guarnecido.',
        unit: 'm2',
        base_price: 26,
        price_min: 22,
        price_max: 32,
        source_kind: 'mixed',
        labour_hours: 0.45,
        labour_category: 'of.1',
        material_anchor: 'ladrillo cerámico y mortero',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'ALB-002',
        name: 'Maestreado y enfoscado de mortero de cemento en paredes',
        description: 'Enfoscado maestreado con mortero de cemento sobre paramentos verticales para posterior alicatado.',
        unit: 'm2',
        base_price: 16.5,
        price_min: 14,
        price_max: 21,
        source_kind: 'mixed',
        labour_hours: 0.35,
        labour_category: 'of.1',
        material_anchor: 'cemento y morteros',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'ALB-003',
        name: 'Ejecución de solera autonivelante (3-5 cm)',
        description: 'Formación de recrecido de suelo con mortero autonivelante para regularización de base de solado.',
        unit: 'm2',
        base_price: 18,
        price_min: 15,
        price_max: 23,
        source_kind: 'mixed',
        labour_hours: 0.28,
        labour_category: 'of.1',
        material_anchor: 'cemento y morteros',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'ALB-004',
        name: 'Ayudas de albañilería a instalaciones (fontanería/electricidad)',
        description: 'Apertura y tapado de rozas, rematado de cajas de mecanismos y pasos de tuberías en obra.',
        unit: 'vg',
        base_price: 350,
        price_min: 280,
        price_max: 450,
        source_kind: 'labour',
        labour_hours: 4.5,
        labour_category: 'of.1',
        material_anchor: null,
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'ALB-005',
        name: 'Colocación de premarco de puerta de paso',
        description: 'Suministro y recibida con yeso/mortero de premarco de pino para puerta de paso.',
        unit: 'ud',
        base_price: 35,
        price_min: 28,
        price_max: 45,
        source_kind: 'mixed',
        labour_hours: 0.35,
        labour_category: 'of.2',
        material_anchor: 'madera de pino',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'ALB-006',
        name: 'Apertura de hueco en muro de carga con cargadero/dintel (incluido apuntalamiento)',
        description: 'Apertura de hueco en muro de carga para paso o ventana (hasta 1,20 m), con apuntalamiento, cargadero metálico o dintel de hormigón y remate de jambas.',
        unit: 'ud',
        base_price: 480,
        price_min: 380,
        price_max: 620,
        source_kind: 'mixed',
        labour_hours: 5,
        labour_category: 'of.1',
        material_anchor: 'perfil de acero / dintel',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
    ],
  },
  {
    name: 'Solados y Alicatados',
    services: [
      {
        code: 'SOL-001',
        name: 'Alicatado de paramento vertical con gres cerámico (colocación)',
        description: 'Mano de obra y material de agarre (cemento cola C2TE) para colocación de azulejos (material cerámico no incluido).',
        unit: 'm2',
        base_price: 24,
        price_min: 20,
        price_max: 30,
        source_kind: 'mixed',
        labour_hours: 0.55,
        labour_category: 'of.1',
        material_anchor: 'cemento cola C2TE',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'SOL-002',
        name: 'Solado de gres porcelánico gran formato (colocación)',
        description: 'Mano de obra y cemento cola flexible tipo C2TES1 para colocación de porcelánico hasta 120x60 cm con crucetas autonivelantes.',
        unit: 'm2',
        base_price: 29,
        price_min: 25,
        price_max: 36,
        source_kind: 'mixed',
        labour_hours: 0.6,
        labour_category: 'of.1',
        material_anchor: 'cemento cola C2TES1',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'SOL-003',
        name: 'Rejuntado de azulejos/baldosas con junta deformable',
        description: 'Aplicación de pasta de rejuntar antihumedad en juntas de pared o suelo, limpiado y pulido final.',
        unit: 'm2',
        base_price: 4.5,
        price_min: 3.5,
        price_max: 6,
        source_kind: 'mixed',
        labour_hours: 0.1,
        labour_category: 'peón',
        material_anchor: 'mortero de juntas',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'SOL-004',
        name: 'Colocación de rodapié cerámico o de madera',
        description: 'Suministro de agarre/adhesivo y colocación de rodapié en perímetro de estancia.',
        unit: 'ml',
        base_price: 7.5,
        price_min: 6,
        price_max: 10,
        source_kind: 'material',
        labour_hours: 0.12,
        labour_category: 'of.2',
        material_anchor: 'rodapié cerámico / madera',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'SOL-005',
        name: 'Impermeabilización de plato de ducha en obra',
        description: 'Aplicación de lámina impermeable tipo Kermate u homóloga en zona de ducha con solape en paredes.',
        unit: 'ud',
        base_price: 110,
        price_min: 85,
        price_max: 140,
        source_kind: 'mixed',
        labour_hours: 1.1,
        labour_category: 'of.1',
        material_anchor: 'lámina impermeable',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'SOL-006',
        name: 'Regularización de paredes con mortero de reparación (hasta 2 cm) antes de alicatar',
        description: 'Regularización de paramentos verticales con mortero de reparación (hasta 2 cm) para dejar el soporte plano y apto para alicatado.',
        unit: 'm2',
        base_price: 13,
        price_min: 10,
        price_max: 17,
        source_kind: 'mixed',
        labour_hours: 0.3,
        labour_category: 'of.1',
        material_anchor: 'mortero de reparación',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
    ],
  },
  {
    name: 'Fontanería, Saneamiento y Calefacción',
    services: [
      {
        code: 'FON-001',
        name: 'Instalación completa de fontanería para baño (agua fría/caliente)',
        description: 'Instalación en tubería multicapa o PEX para lavabo, inodoro, bidet y ducha, con llaves de corte individuales.',
        unit: 'ud',
        base_price: 520,
        price_min: 450,
        price_max: 620,
        source_kind: 'material',
        labour_hours: 6,
        labour_category: 'espec.',
        material_anchor: 'tubería multicapa / PEX',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'FON-002',
        name: 'Instalación completa de fontanería para cocina',
        description: 'Tomas de agua y desagües para fregadero, lavavajillas y lavadora con llaves de escuadra cromadas.',
        unit: 'ud',
        base_price: 420,
        price_min: 350,
        price_max: 500,
        source_kind: 'material',
        labour_hours: 5,
        labour_category: 'espec.',
        material_anchor: 'tubería multicapa / PEX',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'FON-003',
        name: 'Montaje e instalación de sanitario (inodoro/lavabo)',
        description: 'Fijación, conexión de desagüe y agua, y sellado con silicona neutra antimoho de inodoro o lavabo con pedestal/mueble.',
        unit: 'ud',
        base_price: 75,
        price_min: 60,
        price_max: 95,
        source_kind: 'material',
        labour_hours: 0.9,
        labour_category: 'espec.',
        material_anchor: 'sanitario (porcelana)',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'FON-004',
        name: 'Montaje de plato de ducha de resina/carga mineral',
        description: 'Colocación, nivelado, conexión de válvula de gran caudal y sellado de plato de ducha.',
        unit: 'ud',
        base_price: 130,
        price_min: 100,
        price_max: 160,
        source_kind: 'material',
        labour_hours: 1.5,
        labour_category: 'espec.',
        material_anchor: 'resina / carga mineral',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'FON-005',
        name: 'Montaje de mampara de ducha (frontal o angular)',
        description: 'Instalación y fijación a pared de mampara de vidrio templado, ajuste de rodamientos y sellado.',
        unit: 'ud',
        base_price: 95,
        price_min: 80,
        price_max: 120,
        source_kind: 'material',
        labour_hours: 1.1,
        labour_category: 'espec.',
        material_anchor: 'vidrio templado',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'FON-006',
        name: 'Instalación o sustitución de radiador de aluminio',
        description: 'Montaje de radiador por elementos, llaves termostáticas, detentor, purgador y conexionado a red de calefacción.',
        unit: 'ud',
        base_price: 140,
        price_min: 115,
        price_max: 175,
        source_kind: 'material',
        labour_hours: 1.6,
        labour_category: 'espec.',
        material_anchor: 'aluminio (radiador)',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'FON-007',
        name: 'Suministro e instalación de termo eléctrico ACS 100 l',
        description: 'Suministro y montaje de termo eléctrico de 100 l para ACS, con llaves de corte, conexiones flexibles, purga de aire y prueba de estanqueidad.',
        unit: 'ud',
        base_price: 380,
        price_min: 300,
        price_max: 480,
        source_kind: 'material',
        labour_hours: 2.2,
        labour_category: 'espec.',
        material_anchor: 'termo eléctrico (acero)',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
    ],
  },
  {
    name: 'Electricidad e Iluminación',
    services: [
      {
        code: 'ELE-001',
        name: 'Punto de luz sencillo / conmutado (cableado y tubo ondulado)',
        description: 'Suministro e instalación de punto de luz con tubo corrugado libre de halógenos, cable de 1,5 mm2 y caja de registro.',
        unit: 'ud',
        base_price: 42,
        price_min: 35,
        price_max: 50,
        source_kind: 'mixed',
        labour_hours: 0.55,
        labour_category: 'espec.',
        material_anchor: 'cable de cobre',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'ELE-002',
        name: 'Punto de toma de corriente (enchufe 16A con toma de tierra)',
        description: 'Instalación de línea de enchufe con conductor de 2,5 mm2, tubo corrugado y caja de empotrar.',
        unit: 'ud',
        base_price: 45,
        price_min: 38,
        price_max: 55,
        source_kind: 'mixed',
        labour_hours: 0.6,
        labour_category: 'espec.',
        material_anchor: 'cable de cobre',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'ELE-003',
        name: 'Sustitución e instalación de Cuadro General de Mando y Protección (CGMP)',
        description: 'Cuadro de superficie o empotrar hasta 24 elementos con IGA, diferencial de alta sensibilidad y PIA por circuito.',
        unit: 'ud',
        base_price: 380,
        price_min: 300,
        price_max: 460,
        source_kind: 'material',
        labour_hours: 3.5,
        labour_category: 'espec.',
        material_anchor: 'aparamenta (IGA, diferencial, PIA)',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'ELE-004',
        name: 'Toma de red de datos (RJ45 Cat 6) o Coaxial TV',
        description: 'Instalación de toma para televisión o datos con cable apantallado Cat 6 hasta cuadro de comunicaciones.',
        unit: 'ud',
        base_price: 55,
        price_min: 45,
        price_max: 68,
        source_kind: 'material',
        labour_hours: 0.7,
        labour_category: 'espec.',
        material_anchor: 'cable Cat 6',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'ELE-005',
        name: 'Montaje de mecanismo eléctrico (marco + tecla/enchufe)',
        description: 'Instalación y conexionado de mecanismo (tipo Simon 27/82, Niessen Zenit o similar).',
        unit: 'ud',
        base_price: 9,
        price_min: 7,
        price_max: 12,
        source_kind: 'material',
        labour_hours: 0.15,
        labour_category: 'espec.',
        material_anchor: 'mecanismo eléctrico',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'ELE-006',
        name: 'Instalación de foco LED empotrable / downlight',
        description: 'Apertura de hueco en falso techo de pladur y montaje de foco LED con driver.',
        unit: 'ud',
        base_price: 18,
        price_min: 14,
        price_max: 24,
        source_kind: 'material',
        labour_hours: 0.2,
        labour_category: 'espec.',
        material_anchor: 'luminaria LED + driver',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'ELE-007',
        name: 'Circuito completo desde CGMP (cableado, tubo y protecciones)',
        description: 'Circuito completo desde el cuadro general: tubo corrugado libre de halógenos, cable de 2,5 mm2, cajas de derivación y protección magnetotérmica (PIA).',
        unit: 'ud',
        base_price: 135,
        price_min: 110,
        price_max: 170,
        source_kind: 'mixed',
        labour_hours: 1.8,
        labour_category: 'espec.',
        material_anchor: 'cable de cobre',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
    ],
  },
  {
    name: 'Pladur, Techos y Aislamientos',
    services: [
      {
        code: 'PLA-001',
        name: 'Falso techo continuo de placa de cartón yeso (Pladur) 13 mm',
        description: 'Estructura metálica suspendida de perfiles TC60 y placa N13, incluyendo cintas y amasado de juntas.',
        unit: 'm2',
        base_price: 26.5,
        price_min: 22,
        price_max: 32,
        source_kind: 'mixed',
        labour_hours: 0.45,
        labour_category: 'of.1',
        material_anchor: 'placa de yeso + perfilería',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'PLA-002',
        name: 'Tabique de cartón yeso autoportante con aislamiento (15+46+15 mm)',
        description: 'Doble placa a cada lado con perfilería de 46 mm e interior relleno de lana de roca aislante acústico.',
        unit: 'm2',
        base_price: 38,
        price_min: 32,
        price_max: 45,
        source_kind: 'mixed',
        labour_hours: 0.6,
        labour_category: 'of.1',
        material_anchor: 'placa, perfil y lana de roca',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'PLA-003',
        name: 'Falso techo hidrófugo para baño/cocina (placa verde WR)',
        description: 'Falso techo continuo con placa resistente a la humedad tipo Pladur WR de 13 mm.',
        unit: 'm2',
        base_price: 29.5,
        price_min: 25,
        price_max: 35,
        source_kind: 'mixed',
        labour_hours: 0.5,
        labour_category: 'of.1',
        material_anchor: 'placa de yeso WR',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'PLA-004',
        name: 'Formación de cortinero o foseado periférico para tiras LED',
        description: 'Ejecución manual de remate en falso techo para alojamiento de cortinero o luz ambiental indirecta.',
        unit: 'ml',
        base_price: 22,
        price_min: 18,
        price_max: 28,
        source_kind: 'mixed',
        labour_hours: 0.32,
        labour_category: 'of.1',
        material_anchor: 'perfilería',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'PLA-005',
        name: 'Trasdosado autoportante 13+46 con lana mineral (pared)',
        description: 'Trasdosado autoportante de placa de 13 mm sobre perfil de 46 mm con lana mineral de 40 mm en su interior, incluido tratamiento de juntas.',
        unit: 'm2',
        base_price: 33,
        price_min: 28,
        price_max: 40,
        source_kind: 'mixed',
        labour_hours: 0.55,
        labour_category: 'of.1',
        material_anchor: 'placa, perfil 46 y lana mineral',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'PLA-006',
        name: 'Aislamiento acústico de tabique existente (lana mineral 40 mm + trasdosado simple)',
        description: 'Aislamiento acústico de tabique existente con lana mineral de 40 mm y trasdosado simple de placa de 13 mm, con cintas y amasado de juntas.',
        unit: 'm2',
        base_price: 24,
        price_min: 20,
        price_max: 29,
        source_kind: 'mixed',
        labour_hours: 0.4,
        labour_category: 'of.1',
        material_anchor: 'lana mineral 40 mm',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
    ],
  },
  {
    name: 'Pintura y Acabados',
    services: [
      {
        code: 'PIN-001',
        name: 'Alisado de gotelé en paredes y techos (2 manos de tendido)',
        description: 'Rascado o fijado de gota existente, tendido de 2 manos de masilla de renovación (tipo Aguaplast) y lijado fino.',
        unit: 'm2',
        base_price: 14.5,
        price_min: 12,
        price_max: 18,
        source_kind: 'mixed',
        labour_hours: 0.22,
        labour_category: 'of.1',
        material_anchor: 'masilla de renovación',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'PIN-002',
        name: 'Pintado con pintura plástica mate lavable (2 manos)',
        description: 'Aplicación de imprimación selladora y dos manos de pintura plástica de primera calidad en color blanco o suave.',
        unit: 'm2',
        base_price: 8.5,
        price_min: 7,
        price_max: 11,
        source_kind: 'mixed',
        labour_hours: 0.14,
        labour_category: 'of.1',
        material_anchor: 'pintura plástica + imprimación',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'PIN-003',
        name: 'Esmaltado al agua de puertas de paso / armarios',
        description: 'Lijado, imprimación y aplicación de 2 manos de esmalte laca sintético al agua en color blanco sobre puertas existentes.',
        unit: 'ud',
        base_price: 85,
        price_min: 70,
        price_max: 110,
        source_kind: 'mixed',
        labour_hours: 1.1,
        labour_category: 'of.1',
        material_anchor: 'esmalte al agua',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'PIN-004',
        name: 'Tratamiento fijador antimoho y antihumedad en techos de baño',
        description: 'Limpieza química de manchas de moho, aplicación de fondo fijador e imprimación antimoho.',
        unit: 'm2',
        base_price: 12,
        price_min: 9.5,
        price_max: 15,
        source_kind: 'mixed',
        labour_hours: 0.18,
        labour_category: 'of.1',
        material_anchor: 'fondo fijador antimoho',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'PIN-005',
        name: 'Pintura de fachada exterior impermeabilizante (imprimación + 2 manos)',
        description: 'Preparación del soporte, imprimación y dos manos de pintura impermeabilizante elástica en fachada exterior, con protección de huecos y remates.',
        unit: 'm2',
        base_price: 14,
        price_min: 11,
        price_max: 18,
        source_kind: 'mixed',
        labour_hours: 0.22,
        labour_category: 'of.1',
        material_anchor: 'pintura impermeabilizante de fachada',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'PIN-006',
        name: 'Esmaltado de radiadores (lijado, imprimación y 2 manos de esmalte)',
        description: 'Desmontaje, lijado, imprimación antioxidante y dos manos de esmalte al agua sobre radiadores existentes.',
        unit: 'ud',
        base_price: 45,
        price_min: 35,
        price_max: 60,
        source_kind: 'mixed',
        labour_hours: 0.55,
        labour_category: 'of.1',
        material_anchor: 'esmalte + imprimación',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
    ],
  },
  {
    name: 'Carpintería de Madera y Cerrajería',
    services: [
      {
        code: 'CAR-001',
        name: 'Suministro e instalación de puerta de paso MDF lacada en blanco',
        description: 'Puerta de diseño moderno, tapajuntas de 7/9 cm, bisagras/pernios inox y manilla con condena en baño.',
        unit: 'ud',
        base_price: 240,
        price_min: 200,
        price_max: 290,
        source_kind: 'material',
        labour_hours: 1.6,
        labour_category: 'of.1',
        material_anchor: 'puerta MDF lacada',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'CAR-002',
        name: 'Instalación de suelo laminado flotante AC5 (mano de obra + aislante)',
        description: 'Colocación de manta aislante de polietileno y montaje de tarima flotante sintética AC5 clase 33.',
        unit: 'm2',
        base_price: 13.5,
        price_min: 11,
        price_max: 17,
        source_kind: 'material',
        labour_hours: 0.25,
        labour_category: 'of.1',
        material_anchor: 'tarima AC5 + manta aislante',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'CAR-003',
        name: 'Frente de armario empotrado corredero o abatible lacado',
        description: 'Fabricación e instalación de frente de armario lacado en blanco con perfiles de aluminio y tiradores embutidos.',
        unit: 'm2',
        base_price: 180,
        price_min: 150,
        price_max: 230,
        source_kind: 'material',
        labour_hours: 1.4,
        labour_category: 'of.1',
        material_anchor: 'frente lacado + perfiles de aluminio',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'CAR-004',
        name: 'Revestimiento interior de armario en melamina con baldas y cajonera',
        description: 'Forrado de interior de armario empotrado con melamina de 16 mm, módulo de cajones y barra de colgar.',
        unit: 'm2',
        base_price: 140,
        price_min: 115,
        price_max: 170,
        source_kind: 'material',
        labour_hours: 1.2,
        labour_category: 'of.1',
        material_anchor: 'tablero de melamina 16 mm',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'CAR-005',
        name: 'Ventana de PVC con rotura de puente térmico y persiana (hasta 1,20×1,20 m)',
        description: 'Suministro e instalación de ventana de PVC con rotura de puente térmico, doble acristalamiento y persiana de aluminio con lama rellena (hasta 1,20x1,20 m).',
        unit: 'ud',
        base_price: 480,
        price_min: 400,
        price_max: 620,
        source_kind: 'material',
        labour_hours: 3,
        labour_category: 'of.1',
        material_anchor: 'perfil de PVC, vidrio y persiana',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'CAR-006',
        name: 'Puerta de entrada blindada clase 3 (3 puntos, mirilla y herrajes de seguridad)',
        description: 'Suministro e instalación de puerta de entrada blindada clase 3, con tres puntos de cerradura, mirilla, bisagras de seguridad y tapajuntas.',
        unit: 'ud',
        base_price: 1250,
        price_min: 1000,
        price_max: 1600,
        source_kind: 'material',
        labour_hours: 3.5,
        labour_category: 'of.1',
        material_anchor: 'puerta blindada (acero)',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
    ],
  },
  {
    name: 'Climatización y Aire Acondicionado',
    services: [
      {
        code: 'CLI-001',
        name: 'Preinstalación de aire acondicionado por conductos en vivienda',
        description: 'Tirada de líneas de cobre frigorífico aislado, mangueras eléctricas de interconexión y tubo de desagüe anticondensación hasta 10 m.',
        unit: 'ud',
        base_price: 450,
        price_min: 380,
        price_max: 550,
        source_kind: 'material',
        labour_hours: 3.5,
        labour_category: 'espec.',
        material_anchor: 'línea de cobre frigorífico',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'CLI-002',
        name: 'Instalación de equipo de aire acondicionado Split 1x1 (hasta 3 m)',
        description: 'Montaje de unidad interior y exterior, soportes de pared con silentblocks, paso de muro, abocardado y prueba de estanqueidad.',
        unit: 'ud',
        base_price: 220,
        price_min: 180,
        price_max: 270,
        source_kind: 'mixed',
        labour_hours: 2,
        labour_category: 'espec.',
        material_anchor: null,
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'CLI-003',
        name: 'Fabricación y montaje de red de conductos de fibra tipo Climaver',
        description: 'Conductos de lana de vidrio de alta densidad para distribución de aire en falso techo con rejillas de impulsión y retorno.',
        unit: 'ml',
        base_price: 38,
        price_min: 32,
        price_max: 46,
        source_kind: 'material',
        labour_hours: 0.45,
        labour_category: 'espec.',
        material_anchor: 'conducto de fibra de vidrio',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'CLI-004',
        name: 'Instalación de multisplit 2x1 (unidad exterior + 2 interiores, hasta 6 m)',
        description: 'Instalación de equipo multisplit 2x1 (una unidad exterior y dos interiores) con líneas frigoríficas hasta 6 m, soportes, desagües y prueba de estanqueidad.',
        unit: 'ud',
        base_price: 420,
        price_min: 350,
        price_max: 520,
        source_kind: 'mixed',
        labour_hours: 3.2,
        labour_category: 'espec.',
        material_anchor: null,
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'CLI-005',
        name: 'Recarga de gas refrigerante y puesta en marcha (RITE)',
        description: 'Recarga de gas refrigerante R32/R410A con detección de fugas, vacío y puesta en marcha del equipo conforme a RITE.',
        unit: 'ud',
        base_price: 120,
        price_min: 95,
        price_max: 160,
        source_kind: 'material',
        labour_hours: 1,
        labour_category: 'espec.',
        material_anchor: 'gas refrigerante R32/R410A',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'CLI-006',
        name: 'Suministro y montaje de máquina de conductos con distribución hasta 4 rejillas',
        description: 'Suministro y montaje de máquina de conductos con red de distribución de fibra hasta cuatro rejillas de impulsión y retorno, y puesta en marcha.',
        unit: 'ud',
        base_price: 1450,
        price_min: 1150,
        price_max: 1800,
        source_kind: 'material',
        labour_hours: 8,
        labour_category: 'espec.',
        material_anchor: 'máquina de conductos, rejillas',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
    ],
  },
  {
    name: 'Trámites y legalizaciones',
    services: [
      {
        code: 'TRM-001',
        name: 'Boletín eléctrico (Certificado de Instalación Eléctrica, CIE) con tramitación',
        description: 'Emisión y tramitación del Certificado de Instalación Eléctrica (boletín) ante el organismo de industria competente, incluida la tasa de registro.',
        unit: 'ud',
        base_price: 180,
        price_min: 140,
        price_max: 240,
        source_kind: 'admin-fee',
        labour_hours: 1.5,
        labour_category: 'téc.',
        material_anchor: 'tasa de registro',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'TRM-002',
        name: 'Certificado de instalación térmica / boletín ITIAC con tramitación',
        description: 'Emisión y tramitación del certificado de instalación térmica / boletín ITIAC de fontanería y calefacción, incluida la tasa de registro.',
        unit: 'ud',
        base_price: 150,
        price_min: 120,
        price_max: 200,
        source_kind: 'admin-fee',
        labour_hours: 1.2,
        labour_category: 'téc.',
        material_anchor: 'tasa de registro',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'TRM-003',
        name: 'Licencia de obra menor o declaración responsable + tasa municipal',
        description: 'Redacción y presentación de la licencia de obra menor o declaración responsable ante el ayuntamiento, incluida la tasa municipal (varía según municipio).',
        unit: 'ud',
        base_price: 220,
        price_min: 120,
        price_max: 400,
        source_kind: 'admin-fee',
        labour_hours: 1.5,
        labour_category: 'téc.',
        material_anchor: 'tasa municipal (ordenanza)',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
      {
        code: 'TRM-004',
        name: 'Certificado de eficiencia energética (CEE) registrado',
        description: 'Emisión, registro y tramitación del certificado de eficiencia energética (CEE) de la vivienda.',
        unit: 'ud',
        base_price: 130,
        price_min: 90,
        price_max: 180,
        source_kind: 'admin-fee',
        labour_hours: 1.2,
        labour_category: 'téc.',
        material_anchor: 'tasa de registro CEE',
        price_source: DEFAULT_CATALOG_PRICE_SOURCE,
        price_source_url: null,
        price_reviewed_at: DEFAULT_CATALOG_REVISION,
      },
    ],
  },
]
